debug: true

server:
  port: 8080

spring:
 #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/anluo_campus?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

tree:
  file:
    localPath: C:/files/
    baseDomain: http://192.168.1.10:80/files/


